vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set autoindent")
vim.cmd("set smartindent")
vim.cmd("set cindent")
vim.cmd("set hlsearch")
vim.g.mapleader = " "
vim.keymap.set("n", "<C-s>", "<Cmd>:w!<CR>", {})
vim.keymap.set("n", "<C-r>", "<Cmd>:qa!<CR>", {})
vim.keymap.set("n", "<C-v>", "<Cmd>:vsplit<CR>", {})
vim.keymap.set("n", "<C-h>", "<Cmd>:split<CR>", {})
vim.keymap.set("n", "<C-r>", "<Cmd>:qa!<CR>", {})
vim.keymap.set("n", "<A-j>", "<C-W><Left><C-W><CR>", {})
vim.keymap.set("n", "<A-k>", "<C-W><Down><C-W><CR>", {})
vim.keymap.set("n", "<A-l>", "<C-W><Right><C-W><CR>", {})
vim.keymap.set("n", "<A-i>", "<C-W><Up><C-W><CR>", {})
vim.keymap.set("n", "<A-q>", "<C-W><C-Q><C-W>", {})
-- Key mapping for visual mode
vim.keymap.set({'n', 'v'}, "<C-c>", '"+y', {})
